# Generated by Django 3.2.25 on 2024-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.IntegerField()),
                ('branch_name', models.CharField(max_length=15)),
                ('customer_name', models.CharField(max_length=25)),
                ('account_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
